### PR TITLE
Fix TCP support

### LINKED ISSUE #76: Newline is missing at the end of the metric thus breaking TCP support
New lines are not being appended to the metric (https://github.com/reinh/statsd/blob/3863a1a341d21b3c81a0ab9aebc6bd901da45323/lib/statsd.rb#L502), and therefore breaks TCP (since newlines are mandatory in TCP, see 
https://github.com/statsd/statsd/blob/3a3ced99de00855dfc0a45386f466ad5a8d8a549/docs/server.md).

### PR DESCRIPTION
**Pull request by bilbof**
Fixes #76.

As [described by Statsd](https://github.com/statsd/statsd/blob/3a3ced99de00855dfc0a45386f466ad5a8d8a549/docs/server.md), "each metric must be terminated by the \n character when received over TCP". I've tested this fix against Statsd and found that it works.

### CODE REVIEW

**Comment by bilbof** [comment]
It looks like Travis is a bit unhappy. I'll be happy to help fix Travis if you need a hand with that (do the Github Actions builds overlap what Travis is doing?).

File: lib/statsd.rb [hunk 1]
```diff
@@ -476,9 +476,11 @@ def send_to_socket(message)
       # send(2) is atomic, however, in stream cases (TCP) the socket is left
       # in an inconsistent state if a partial message is written. If that case
       # occurs, the socket is closed down and we retry on a new socket.
-      n = socket.write(message)
+      l = @protocol == :tcp ? message.length + 1 : message.length
+      br = @protocol == :tcp ? "\n" : ""
+      n = socket.write(message + br)
 
-      if n == message.length
+      if n == l
```
Comment (raggi) [inline lib/statsd.rb:483]: in githubs chosen font, i can't tell if this is a 1 or an l, so it's a readability problem. Could you use len or length?

I think it might be just as easy to write this:

```ruby
message = @protocol == :tcp ? message + "\n" : message
n = socket.write(message)
if n == message.length
```

Comment (bilbof) [reply lib/statsd.rb]: Thanks @raggi - you're right, that looks better! I've amended the commit.

**Comment by bilbof** [comment]
@raggi the gentlest of nudges here, would it be possible to merge this PR? 🙂

**Comment by raggi** [comment]
Release in 1.5
