### PR TITLE
better thread safety and socket semantics

### LINKED ISSUE #55: multiple calls to Statsd.new doesn't recreate socket, address family conflicts
I'm using the IPv6 support from PR #46.

Because it uses only a single per-thread socket and the creation of the socket happens only once, calling `.new` again with a hostname that is either a literal address of another address family or a name that resolves to only an address of another address family, it stops being able to send because `sendto(2)` fails with `EAFNOSUPPORT (Address family not supported by protocol)`, and stats are silently discarded.
```
$statsd1 = Statsd.new '127.0.0.1', 9125 # socket type is AF_INET, seen in lsof
$statsd1.increment "abc"
$statsd2 = Statsd.new '::1', 9125 # socket type should be AF_INET6, but is not
$statsd2.increment "abc" # sendto(2) errors out, seen in strace
```
Because `Thread.current[:statsd_socket]` is already defined, the object instance returned by the second call to `.new`, `$statsd2`, can't use the IPv4 socket created from the first call.

Creating multiple instances might be done if you wanted to use multiple statsd servers for different kinds of metrics.  Right now, you can call `.new` again but it only works if the address family of the hostname in the second call is the same as the first.  This problem will also come up if DNS returns either A or AAAA records (but not both) on subsequent attempts to send.

I see a couple of fixes, and which one is appropriate is based on how you intent for this library to work.

1) If you want this library to produce a singleton instance as the result of calling `.new`, then when .new is called, if `Thread.current[:statsd_socket]` is a socket, close it and set it to nil.  The next time `.socket` is called, it will create a new socket of the appropriate address family that matches the address family of the hostname passed.  The object returned is effectively (thread) global even if the variable holding the instance isn't a ruby global variable.

2) Recreate a socket of the appropriate address family on every call to `send_to_socket`, or perhaps only do that conditionally by storing the address family of the last created socket in thread local storage and only recreating it if the address family of the latest hostname used is a different address family.

3) Make it support multiple instances by storing the socket in the object instance instead in thread local storage.  This way, each call to `.new` gets its own socket that matches the address family of the hostname passed in.

4) Convert to a UDP "connected" socket and store it in the object instance. Connect it at creation time and don't bother to store the hostname and port in the object instance (it would no longer be necessary).  This has the added bonus of not having to do repeated DNS lookups if a hostname (vs an address) is given (negating that warning about performance and nscd in the README).

Since the socket is UDP and has no on-the-wire protocol state to be maintained (unlike, say, a database connection over TCP), there should be no problems with sharing it between threads, so the socket can be stored on the instance object rather than in thread local storage.  This would make options 3 or 4 easy with less code.

The way the docs are written seem to indicate that you should be able to use multiple object instances (and you can, as long as the address family doesn't change), but the way the tests are written exploits the fact that there's only one socket created in TLS (my manipulating it directly to set up the tests).

### PR DESCRIPTION
**Pull request by raggi**
This needs to be a major version change, as it changes a lot of implied
semantics.

Includes addition of a "hup" method that would reconnect the sockets, typically
this would be used in response to a HUP signal.

Closes #55 
Closes #54
Closes #50
Closes #49
Closes #45

Review please @reinh @cheald
cc @thwarted

### CODE REVIEW

**Comment by zanker** [comment]
Hey @raggi, we just got bit by this, since in Sidekiq on JRuby the `Thread.current` changes with each job. Is there anything specific that would need to be done get this merged? Happy to take a look at the work needed.

**Comment by raggi** [comment]
@zanker I was mostly just hoping for a code review, but none presented.

**Comment by thwarted** [comment]
I looked it over, but I don't have much to add because my ruby-fu is weak.

File: lib/statsd.rb [hunk 1]
```diff
@@ -196,16 +211,16 @@ def send_to_socket(message)
...
       end
-      socket.readline # clear the closing newline out of the socket
+      @socket.readline # clear the closing newline out of the socket
       buffer
     end
 
-    def socket
-      Thread.current[:statsd_admin_socket] ||= TCPSocket.new(host, port)
+    def connect
+      @s_mu.synchronize { @socket = TCPSocket.new(host, port) }
```
Comment (zanker) [inline lib/statsd.rb]: Since you call this on `port=` and `host=`, should check that `@socket` is set and if it is call `@socket.close`. Technically, it'll get GCed eventually but if we can explicitly close it we should.

File: lib/statsd.rb [hunk 2]
```diff
@@ -391,10 +416,11 @@ def send_stats(stat, delta, type, sample_rate=1)
   end
 
   def socket
-    Thread.current[:statsd_socket] ||= UDPSocket.new addr_family
+    @socket || raise(ThreadError, "socket missing")
   end
 
-  def addr_family
-    Addrinfo.udp(@host, @port).afamily
+  def connect
```
Comment (zanker) [inline lib/statsd.rb]: Same here with making sure to call `@socket.close` if it's set

File: lib/statsd.rb [hunk 3]
```diff
@@ -369,11 +388,17 @@ def batch(&block)
     Batch.new(self).easy &block
   end
 
+  # Reconnects the socket, useful if the address of the statsd has changed. This
+  # method is not thread safe.
+  def hup
```
Comment (zanker) [inline lib/statsd.rb]: Would just move `connect` up here since it's just an alias.

Comment (gaffneyc) [inline lib/statsd.rb]: That sounds like a good suggestion.

An alternative approach would be to open a socket per query instead of keeping it open for the admin piece. While not great it would remove the need for a mutex.

File: lib/statsd.rb (hunk 1 above)
Comment (gaffneyc) [inline lib/statsd.rb]: I would suggest removing the `connect` call form `host=` and `port=`. If the host at the port change then there is no way to change them together.

**Comment by raggi** [comment]
I have updated this to respond to the review comments (thanks all).

Note that this solution is insufficient to support #61 which does not maintain thread safety (TCP writes are not necessarily thread safe).

**Comment by raggi** [comment]
@reinh PTAL.

**Comment by raggi** [comment]
And squashed.

**Comment by reinh** [comment]
@raggi Replacing a thread-local socket with an instance variable and wrapping use-sites with a mutex? Seems good. What's up with CI? What's our plan for #61? Land this first and then continue with TCP support?
